import type { Metadata } from 'next'
import { Wix_Madefor_Display } from 'next/font/google'
import '@/styles/global.scss'
import { Header } from '@/components/Header'
import { clsx } from 'clsx'
import { Hero } from '@/components/Hero'

const wixMadeforDisplay = Wix_Madefor_Display({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-[#ffffff]">
      <body
        className={clsx(
          wixMadeforDisplay.className,
          'mx-auto w-full max-w-[1280px] px-[10px] pb-[100px] sm:px-[25px]',
          'selection:bg-black selection:text-white',
        )}
      >
        <Header />
        <div className="h-[20px]" />
        {children}
      </body>
    </html>
  )
}
