import type { Metadata } from "next";
import { Wix_Madefor_Display } from "next/font/google";
import "@/styles/global.scss";
import { Header } from "@/components/Header";
import {clsx} from 'clsx'
import { Hero } from "@/components/Hero";

const wixMadeforDisplay = Wix_Madefor_Display({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(wixMadeforDisplay.className,'xl:w-[1500px] w-full mx-auto pb-[100px] px-[10px]')}>
        <Header />
        <div className="h-[20px]" />
        {children}
      </body>
    </html>
  );
}
